@url = http://localhost:5000

### Get all activites
GET {{url}}/activity


### Add a new activity
POST {{url}}/activity
Content-Type: application/json

{
    "Date": "2020-01-30"
}


### Get by id
GET {{url}}/activity/371

### Delete by id
DELETE  {{url}}/activity/517    

### Update by id
PUT {{url}}/activity/371
Content-Type: application/json

{
    "Date": "2100-01-25"
}


### Get Repository Id
GET {{url}}/activity/repid